22/jwt auth 0
selhanaf/ramp-up-backend pull request #13
Opened 2021-02-16 15:59 UTC by selhanaf

2021-02-16 17:08 UTC, darkjeffbr requested changes

2021-02-16 17:08 UTC, darkjeffbr commented on src/main/java/com/car/app/security/AuthenticationFilter.java
> +public class AuthenticationFilter  implements ContainerRequestFilter {
Since this is a request filter, as long as we annotate it with @Provider and @Priority, the custom annotation @SecuredApi is not necessary.

2021-02-16 17:08 UTC, darkjeffbr commented on src/main/java/com/car/app/controller/CarService.java
> +	AuthAPI auth = new AuthAPI("dev-04zom-rc.us.auth0.com", "KntuHyTQxJILx19rQSlJSVuoBw2yoynV",
What is the use of this object ?

2021-02-16 17:08 UTC, darkjeffbr commented on src/main/java/com/car/app/security/AuthenticationFilter.java
> +	AuthAPI auth = new AuthAPI("dev-04zom-rc.us.auth0.com", "ZBg0YCTgMaEBnCcunLo5zph8l78y0htE",
Sensitive information like clientId and clientSecret are stored as enviroment variable or retrieved in a secure way, but write them in the code is not a good practice.

2021-02-17 08:24 UTC, selhanaf commented on src/main/java/com/car/app/controller/CarService.java
> +	AuthAPI auth = new AuthAPI("dev-04zom-rc.us.auth0.com", "KntuHyTQxJILx19rQSlJSVuoBw2yoynV",
I used it in this, so if I can't get the user info, then I'm throwing 401 with invalid token message
![image](https://user-images.githubusercontent.com/78147936/108176110-e1ac3f00-7101-11eb-8dfc-24d682d4ffcf.png)

2021-02-17 10:31 UTC, darkjeffbr approved these changes

2021-02-17 10:31 UTC, merged