6/swagger docs
selhanaf/ramp-up-backend pull request #4
Opened 2021-02-04 11:30 UTC by selhanaf

2021-02-04 13:05 UTC, darkjeffbr requested changes

2021-02-04 13:05 UTC, darkjeffbr commented on src/main/java/com/car/app/resource/CarResource.java
> +@Api(value = "Cars APIs", description = "APIs for cars")
I think this annotation could be added to the interface too.

2021-02-04 13:05 UTC, darkjeffbr commented on src/main/webapp/index.html
> +<!-- HTML for static distribution bundle build -->
It is very nice that you've added the swagger UI.
Usually this is done with a plugin during build time. There are a lot of ways to do it.
What you've done is not wrong is just another way of doing it :smile: .

2021-02-04 13:48 UTC, selhanaf commented on src/main/java/com/car/app/resource/CarResource.java
> +@Api(value = "Cars APIs", description = "APIs for cars")
if I do this, the get car by Id will disappear from the swagger json,
![image](https://user-images.githubusercontent.com/78147936/106901436-0cf16000-66f8-11eb-8316-1277d3dccb03.png)

2021-02-08 10:06 UTC, darkjeffbr approved these changes

2021-02-08 10:06 UTC, merged